project_name: MyProject
folders:
  - .github
  - board/linker
  - board/startup
  - board/system
  - docs
  - project
  - scripts/build
  - scripts/cfg
  - scripts/cmake
  - source/app
  - source/bsp
  - source/configs
  - tests
  - vendors
files:
  - CMakeLists.txt
  - CMakePresets.json
  - README.md